version: 1
services:
  - type: web
    name: notes-app
    env: node
    buildCommand: |
      cd client && yarn install && yarn build
      cd ../server && yarn install
    startCommand: |
      cd server && node index.js
    autoDeploy: true
    plan: free
    envVars:
      NODE_ENV: production
