version: 1
services:
  - type: web
    name: notes-app
    env: node
    buildCommand: cd /opt/render/project/src/client && yarn install && yarn build
    startCommand: cd /opt/render/project/src/server && node index.js
    autoDeploy: true
    plan: free
    envVars:
      NODE_ENV: production
