version: 1
services:
  - type: web
    name: notes-app
    env: node
    buildCommand: cd client && yarn install && yarn build
    startCommand: node server/index.js
    autoDeploy: true
    plan: free
    envVars:
      NODE_ENV: production
